import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header/index";
import SideBar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <SideBar>
            <Header />
            <main className="p-4">
              {children}
            </main>
          </SideBar>
      </body>
    </html>
  );
}