const BASE_URL = process.env.NEXT_PUBLIC_API_URL;
const AUTH_URL = `${BASE_URL}/auth`;
const USER_URL = `${BASE_URL}/user`;
const MASTER = `${BASE_URL}/master`;
const INVENTORY = `${BASE_URL}/inventory`;

export const api = {
    auth: {
        login: `${AUTH_URL}/login`,
        refreshToken: `${AUTH_URL}/refresh-token`,
        logout: `${AUTH_URL}/logout`,
        currentUser: `${AUTH_URL}/current-user`,
    },
    user: {
        allUser: `${USER_URL}/all`,
        signature: `${USER_URL}/signature`,
        allRole: `${USER_URL}/roles`,
        addUser: `${USER_URL}/create`,
        deleteUser: `${USER_URL}/delete`,
    },
    inventory: {
        allInventory: `${BASE_URL}/inventory/master-barang/all`,
        addInventory: `${BASE_URL}/inventory/master-barang/by-id`,
        detailInventory: `${BASE_URL}/inventory/master-barang`,
        updateInventory: `${BASE_URL}/inventory/master-barang`,
        deleteInventory: `${BASE_URL}/inventory/master-barang`,
        allSatuan: `${BASE_URL}/inventory/satuan/all`,
        allStock: `${BASE_URL}/inventory/stock`,
        stockBatch: `${BASE_URL}/inventory/stock/batch`,
        stockHistory: `${BASE_URL}/inventory/stock/history`,
        stockOpname: `${BASE_URL}/inventory/opname`,
        stockOpnameAll: `${BASE_URL}/inventory/opname/all`,
        stockOpnameSync: `${BASE_URL}/inventory/opname/sinkronisasi-stock`,
        stockOpnameDetail: `${BASE_URL}/inventory/opname/detail`,
        allDepartement: `${BASE_URL}/inventory/departements`,
        stockOpnamePrintPDF: `${BASE_URL}/inventory/opname/print-pdf`,
        getListDept: `${INVENTORY}/departements`,
        formDept: `${INVENTORY}/departement`,
    },
    purchase: {
        allPR: `${BASE_URL}/purchase/request/all`,
        allPurchaseRequestForPO: `${BASE_URL}/purchase/request/all-for-po`,
        addPurchaseRequest: `${BASE_URL}/purchase/request`,
        switchGudangPR: `${BASE_URL}/purchase/request/switch-gudang`,
        detailPurchaseRequest: `${BASE_URL}/purchase/request`,
        approvePR: `${BASE_URL}/purchase/request/approve`,
        removePR: `${BASE_URL}/purchase/request`,
        allPO: `${BASE_URL}/purchase/order/all`,
        addPurchaseOrder: `${BASE_URL}/purchase/order`,
        detailPurchaseOrder: `${BASE_URL}/purchase/order`,
        approvePO: `${BASE_URL}/purchase/order/approve`,
        removePO: `${BASE_URL}/purchase/order`,
        addInvoice: `${BASE_URL}/purchase/invoice`,
        allInvoice: `${BASE_URL}/purchase/invoice/all`,
        detailInvoice: `${BASE_URL}/purchase/invoice`,
        pelunasanInvoice: `${BASE_URL}/purchase/invoice/pelunasan`,
        invoiceDaily: `${BASE_URL}/purchase/invoice/daily`,
        invoiceMonthly: `${BASE_URL}/purchase/invoice/monthly`,
        invoiceYearly: `${BASE_URL}/purchase/invoice/yearly`,
        topSupplier: `${BASE_URL}/purchase/invoice/top-supplier`,
        topBuying: `${BASE_URL}/purchase/invoice/top-buying`,
    },
    supplier: {
        allSupplier: `${BASE_URL}/supplier/all`,
    },
    customer: {
        allCustomer: `${BASE_URL}/customer/all`,
        update: `${BASE_URL}/customer`,
        create: `${BASE_URL}/customer`,
    },
    salesOrder: {
        all: `${BASE_URL}/sales/order/all`,
        detail: `${BASE_URL}/sales/order`,
        add: `${BASE_URL}/sales-order`,
        approve: `${BASE_URL}/sales-order/approve`,
        remove: `${BASE_URL}/sales-order`,
        createSO: `${BASE_URL}/sales/order`,
        invoiceSOAll: `${BASE_URL}/sales/invoice/all`,
        invoiceSODetail: `${BASE_URL}/sales/invoice`,
        createInvoice: `${BASE_URL}/sales/invoice`,
        pelunasanInvoice: `${BASE_URL}/sales/invoice/payment`,
        invoiceDaily: `${BASE_URL}/sales/invoice/daily`,
        invoiceMonthly: `${BASE_URL}/sales/invoice/monthly`,
        invoiceYearly: `${BASE_URL}/sales/invoice/yearly`,
        topCustomer: `${BASE_URL}/sales/invoice/top-customer`,
        topSelling: `${BASE_URL}/sales/invoice/top-selling`,
    },
}